version: '3.9'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: echobudget-app
    env_file:
      - ./.env
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - database

  web-proxy:
    image: nginx:1.27.4
    container_name: echobudget-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  rabbitmq:
    image: rabbitmq:4-management
    container_name: echobudget-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    restart: on-failure

  database:
    image: postgres:17
    container_name: echobudget-postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgres_volume:
  rabbitmq_volume:
